CONTIKI_PROJECT = web_server_contiki
all: $(CONTIKI_PROJECT)

CONTIKI = ../../../..

MAKE_MAC = MAKE_MAC_TSCH
include $(CONTIKI)/Makefile.dir-variables

MODULES_REL += webserver

include $(CONTIKI)/Makefile.include
